import turtle
turtle.Pen()
t = turtle
t.shape('turtle')
t.speed()
#t.color('#FDA50F')
t.color('black','#ffe737')
t.begin_fill()
t.goto(45,40)
t.left(110)
t.circle(80,310)
t.left(90)
t.goto(0,0)
t.penup()
t.goto(0,60)
t.pendown()
t.end_fill()
t.color('black')
t.begin_fill()
t.circle(15)
t.end_fill()
t.penup()
t.goto(0,60)
t.pendown()
t.color('white')
t.begin_fill()
t.circle(4)
t.end_fill()
t.penup()
t.goto(1000,1000)

